### ISSUE TITLE
java.lang.ClassCastException 

### ISSUE THREAD

**Issue by hussainahmad** [pavlospt/litho-glide#3]
Hey my code running fine using `Litho-Fresco` but I want to use `Glide`  and I am getting same error again and again , App Crash  
``` FATAL EXCEPTION: main
                                                                                                        Process: com.hussain.progosteach.litho_tab_mvp_elabelz.production, PID: 8153
                                                                                                        java.lang.ClassCastException: com.hussain.progosteach.litho_tab_mvp_elabelz.ui.MainActivity cannot be cast to com.facebook.litho.ComponentContext
                                                                                                            at com.facebook.litho.MountState.setViewBackground(MountState.java:1571)
                                                                                                            at com.facebook.litho.MountState.setViewAttributes(MountState.java:1121)
                                                                                                            at com.facebook.litho.MountState.mountContent(MountState.java:1016)
                                                                                                            at com.facebook.litho.MountState.mountLayoutOutput(MountState.java:964)
                                                                                                            at com.facebook.litho.MountState.mount(MountState.java:217)
                                                                                                            at com.facebook.litho.LithoView.mount(LithoView.java:534)
                                                                                                            at com.facebook.litho.ComponentTree.mountComponent(ComponentTree.java:478)
                                                                                                            at com.facebook.litho.ComponentTree.incrementalMountComponent(ComponentTree.java:430)
                                                                                                            at com.facebook.litho.ComponentTree.mountComponentIfDirty(ComponentTree.java:406)
                                                                                                            at com.facebook.litho.ComponentTree.layout(ComponentTree.java:665)
                                                                                                            at com.facebook.litho.LithoView.performLayout(LithoView.java:229)
                                                                                                            at com.facebook.litho.ComponentHost.onLayout(ComponentHost.java:733)
                                                                                                            at android.view.View.layout(View.java:17995)
                                                                                                            at android.view.ViewGroup.layout(ViewGroup.java:5817)
                                                                                                            at android.support.v7.widget.RecyclerView$LayoutManager.layoutDecoratedWithMargins(RecyclerView.java:8839)
                                                                                                            at android.support.v7.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:685)
                                                                                                            at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1511)
                                                                                                            at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:595)
                                                                                                            at android.support.v7.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
                                                                                                            at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3583)
                                                                                                            at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3312)
                                                                                                            at android.support.v7.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:1648)
                                                                                                            at android.support.v7.widget.RecyclerView$1.run(RecyclerView.java:343)
                                                                                                            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
                                                                                                            at android.view.Choreographer.doCallbacks(Choreographer.java:686)
                                                                                                            at android.view.Choreographer.doFrame(Choreographer.java:619)
                                                                                                            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
                                                                                                            at android.os.Handler.handleCallback(Handler.java:739)
                                                                                                            at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                                            at android.os.Looper.loop(Looper.java:148)
                                                                                                            at android.app.ActivityThread.main(ActivityThread.java:7329)
                                                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)```

**Comment by pavlospt** [comment]
@hussainahmad The context that you are providing to your Component is not a ComponentContext.

**Comment by hussainahmad** [comment]
@pavlospt same code when **uncomment** Fresco code run fine , then hows this possible

**Comment by hussainahmad** [comment]
```

package com.hussain.progosteach.lithoproductdetail_elabelz;

import android.graphics.Color;
import android.graphics.Typeface;

import com.facebook.litho.ClickEvent;
import com.facebook.litho.Column;
import com.facebook.litho.ComponentContext;
import com.facebook.litho.ComponentLayout;
import com.facebook.litho.Row;
import com.facebook.litho.StateValue;
import com.facebook.litho.annotations.LayoutSpec;
import com.facebook.litho.annotations.OnCreateInitialState;
import com.facebook.litho.annotations.OnCreateLayout;
import com.facebook.litho.annotations.OnEvent;
import com.facebook.litho.annotations.OnUpdateState;
import com.facebook.litho.annotations.Param;
import com.facebook.litho.annotations.Prop;
import com.facebook.litho.annotations.ResType;
import com.facebook.litho.annotations.State;
import com.facebook.litho.widget.Image;
import com.facebook.litho.widget.Text;
import com.facebook.yoga.YogaAlign;
import com.facebook.yoga.YogaEdge;
import com.facebook.yoga.YogaPositionType;
import com.github.pavlospt.litho.glide.GlideImage;
import com.hussain.progosteach.lithoproductdetail_elabelz.events.LikeChangeEvent;

//import com.github.pavlospt.litho.glide.GlideImage;

/**
 * Created by Hussain Sherwani
 * on 19-May-17
 */

@LayoutSpec(events = { LikeChangeEvent.class })
public class ListItemSpec {
    @OnCreateInitialState
    static void createInitialState(ComponentContext c, StateValue<Boolean> isLiked, @Prop boolean initLiked) {
        isLiked.set(initLiked);
    }
    @OnCreateLayout
    public static ComponentLayout onCreateLayout(
            ComponentContext c,

            @Prop(optional = true, resType = ResType.COLOR) int color,
            @Prop(optional = true, resType = ResType.INT) int width,
            @Prop(optional = true, resType = ResType.INT) int height,
            @Prop(optional = true, resType = ResType.STRING) String cPrice,
            @Prop(optional = true, resType = ResType.STRING) String manufacturer,
            @Prop(optional = true, resType = ResType.STRING) String uriImage,
            @Prop Typeface cPriceStyle,
            @Prop Typeface manufacturerStyle,
            @State boolean isLiked

    ) {

//        final DraweeController controller = Fresco.newDraweeControllerBuilder()
//                .setUri(uriImage)
//                .build();
        final ComponentLayout column = Column.create(c)
                .backgroundColor(color)
                .child(GlideImage.create(c)
                .imageUrl(uriImage)
                .failureImageRes(R.drawable.loading)
                .placeholderImageRes(R.drawable.loading)
                .withLayout()
                .backgroundColor(Color.WHITE)
                .widthPx(width)
                .heightPx(height)
                )
//                .child(
//                        FrescoImage.create(c)
//                                .controller(controller)
//                                .failureImageRes(R.drawable.loading)
//                                .placeholderImageRes(R.drawable.loading)
//                                .actualImageScaleType(ScalingUtils.ScaleType.FIT_XY)
//                                .withLayout()
//                                .backgroundColor(Color.WHITE)
//                                .widthPx(width)
//                                .heightPx(height)
//                )
                .child(Image.create(c)
                        .drawableRes(isLiked ? R.drawable.fav_active :R.drawable.fav)
                        .withLayout()
                        .clickHandler(ListItem.onLikeButtonClicked(c))
                        .positionType(YogaPositionType.ABSOLUTE)
                        .widthDip(35)
                        .heightDip(35)
                        .paddingDip(YogaEdge.ALL, 8)
                        .alignSelf(YogaAlign.FLEX_START)
                        .build()
                )/*.clickHandler(ListItem.onViewClicked(context))*/
//                .child(
//                        GlideImage.create(c)
//                        .imageUrl(uriImage)
//                                .failureImageRes(R.drawable.loading)
//                                .placeholderImageRes(R.drawable.loading)
//                )
                .child(
                        Text.create(c)
                                .text(cPrice)
                                .textColor(Color.BLACK)
                                .minLines(1)
                                .maxLines(1)
//                                .typeface(Typeface.createFromAsset(c.getAssets(), "font/gotham_bold_webfont.ttf"))
                                .typeface(cPriceStyle)
                                .textSizeSp(12)
                                .withLayout()
                )
                .child(
                        Text.create(c)
                                .text(manufacturer)
                                .textSizeSp(12)
                                .textColor(Color.GRAY)
                                .maxLines(2)
                                .minLines(2)
                                .textSizeSp(12)
//                                .typeface(Typeface.createFromAsset(c.getAssets(), "font/gotham_book_webfont.ttf"))
                                .typeface(manufacturerStyle)
                                .withLayout()
                )
                .build();
        return Row.create(c)
                .paddingDip(YogaEdge.BOTTOM, 3)
                .paddingDip(YogaEdge.TOP, 3)
                .child(column)
                .build();

    }
    @OnUpdateState
    static void updateLikeButton(StateValue<Boolean> isLiked, @Param boolean updatedValue) {
        isLiked.set(updatedValue);
    }

    @OnEvent(ClickEvent.class)
    static void onLikeButtonClicked(ComponentContext c, @State boolean isLiked/*,*//* @FromEvent View view, @Prop View.OnClickListener listener*/) {
//        ListItem.dispatchLikeChangeEvent(ListItem.getLikeChangeEventHandler(c), !isLiked, gif.getId());
//        listener.onClick(view);
        ListItem.updateLikeButtonAsync(c, !isLiked);
//        ListItem
    }

//    @OnEvent(ClickEvent.class)
//    static void onViewClicked(ComponentContext c, @Prop GifItem gif, @Prop (optional = true) GifCallback callback) {
//        if (callback != null) {
//            callback.onGifSelected(gif, c.getComponentScope());
//        }
//    }

//    @OnEvent(FavChangeEvent.class)
//    static void onFavChanged(ComponentContext c, @FromEvent boolean isLiked, @FromEvent String gifId, @Prop Product gif) {
//        if (gif.getId().equals(gifId)) {
//            ListItem.updateLikeButtonAsync(c, isLiked);
//        }
//    }

//    public interface GifCallback {
//        void onGifSelected(Product gif, Component gifComponent);
//    }

}

Please review the code

**Comment by pavlospt** [comment]
@hussainahmad What version of Litho are you trying this with?

**Comment by hussainahmad** [comment]
@pavlospt  I tested with version `0.5.0` and also with `0.3.1`

**Comment by hussainahmad** [comment]
@pavlospt when you created this  `litho-glide` i tested this with `litho V:0.2.1` , that time same code work fine , may be here due to version change getting this error, but I am checking

**Comment by pavlospt** [comment]
@hussainahmad Probably that is the issue, will have to search it a bit more and let you know!

**Comment by pavlospt** [comment]
Have upgraded LithoGlide to be compatible with Litho v0.7.0. Probably I should upgrade it with the latest version as well. Please check if the issue still persists and let me know!
